Add LexDAO & ANJmol space folders
balancer-labs/snapshot pull request #54
Opened 2020-09-02 13:55 UTC by Ro5s

This PR reflects the new space format (as recommended in https://github.com/balancer-labs/snapshot/pull/48). Thanks!

2020-09-02 16:47 UTC, bonustrack approved these changes

2020-09-02 16:47 UTC, bonustrack commented on spaces/anjmol/skin.scss
> +.name {
This should be changed to the space id
```suggestion
.anjmol {
```

2020-09-02 16:47 UTC, bonustrack commented on spaces/lexdao/skin.scss
> +.name {
```suggestion
.lexdao {
```

2020-09-02 16:48 UTC, bonustrack requested changes
can you do the changes i've suggested?

2020-09-02 17:01 UTC, Ro5s commented on spaces/lexdao/skin.scss
> +.name {
many thanks!!

2020-09-02 17:01 UTC, Ro5s commented
I just made the requested changes @bonustrack // appreciate the notes! :smile_cat:

2020-09-02 17:48 UTC, bonustrack commented
@Ro5s If the skins are same as the example (the default skin) then you can remove these files in the PR.

2020-09-02 18:31 UTC, Ro5s commented
I took the opportunity to refresh and add some custom colors to the skin files for LexDAO + ANJmol. Thanks for checking status @bonustrack !

2020-09-04 03:49 UTC, bonustrack commented
@Ro5s This PR need to be updated with base branch, now it's out-of-date.

2020-09-04 14:26 UTC, Ro5s commented
Done! @bonustrack thanks :~)

2020-09-05 02:04 UTC, bonustrack approved these changes

2020-09-05 02:05 UTC, merged